#!/bin/bash
# Copyright (c) 2014, wangdali <wangdali@qq.com>
#

###
#
# 椒图内存缓冲服务器
# 用于缓存静态文件
#
# 请将这个脚本放在 /etc/init.d 目录中
#
###

PROG="jiaotu" ## 程序名称
PROG_IP="127.0.0.1" ## 地址
PROG_PORT="6000" ## 端口
PROG_USER="loong" ## 用户名
PROG_PATH="/opt/loong/bin" ## 服务程序的路径，非必要，但有时会有帮助。
PID_PATH="/opt/loong/var/run" # 服务程序的PID路径
PROG_ARGS="-d" ## 服务程序的其他参数

# 启动服务
start() {
    if [ -e "$PID_PATH/$PROG.pid" ]; then
        ## 程序运行错误，退出。
        echo "Error! $PROG is currently running!" 1>&2
        exit 1
    else
	## 如果你想保存输出，修改 /dev/null 像 /var/log/$PROG 这样。
        $PROG_PATH/$PROG -l $PROG_IP -p $PROG_PORT -u $PROG_USER -P $PID_PATH/$PROG.pid $PROG_ARGS 2>&1 >/dev/null &

        echo "$PROG started"
    fi
}

# 停止服务
stop() {
    echo "begin stop"
    if [ -e "$PID_PATH/$PROG.pid" ]; then
        ## 程序运行，所以停止它。
	pid=$(sed -n 1p $PID_PATH/$PROG.pid)
	kill $pid
        
        rm -f  "$PID_PATH/$PROG.pid"
        echo "$PROG stopped"
    else
        ## 程序没有运行，出错退出。
        echo "Error! $PROG not started!" 1>&2
        exit 1
    fi
}

## 首先检查这个脚本是否以 root 权限运行。
if [ "$(id -u)" != "0" ]; then
    echo "This script must be run as root" 1>&2
    exit 1
fi

# 检查脚本调用参数，并处理
case "$1" in
    start)
        start
        exit 0
    ;;
    stop)
        stop
        exit 0
    ;;
    reload|restart|force-reload)
        stop
        start
        exit 0
    ;;
    **)
        echo "Usage: $0 {start|stop|reload}" 1>&2
        exit 1
    ;;
esac

